% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Nov-2025 15:35:43
%  MATLAB version: 25.2.0.3055257 (R2025b) Update 2
% -------------------------------------------------------------------
saveVarsMat = load('valuez.mat');

z = saveVarsMat.z; % <1x1101 double> too many elements

clear saveVarsMat;
